// Authors the 24 curated looks as JSON from spec Appendix B (§4.5).
//
// Generated rather than hand-typed so the 24 files cannot drift from one another in shape,
// and so a change to the token schema is one edit here instead of 24. The VALUES are the
// spec's; nothing is invented. Run `npm run lint:looks` afterwards — §12.7 checks contrast,
// token completeness and font validity before any of these reaches a user.
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve(import.meta.dirname, "../src/looks");

/** Zone colour sets, Appendix B. */
const ZONES = {
  default: ["#8FA3B5", "#4FC1E9", "#7BE495", "#FFB347", "#FF5A5F"],
  clinical: ["#94A3B8", "#38BDF8", "#34D399", "#FBBF24", "#F43F5E"],
  warm: ["#C9B79C", "#E0A458", "#E8461E", "#B8462E", "#6B1D12"],
  neon: ["#6C63FF", "#00E5FF", "#39FF14", "#FFD300", "#FF2D95"],
  greys: ["#DDDDDD", "#BBBBBB", "#999999", "#666666", "#111111"],
  hot: ["#5A2A2E", "#8E3A40", "#C74B52", "#FF3B4A", "#FFB3B8"],
  sage: ["#B8C4B0", "#93A98C", "#7A9A7E", "#C9A27A", "#B5674D"],
  blues: ["#BFD3FF", "#9FC5FF", "#6FA3FF", "#FFFFFF", "#FFD166"],
  greens: ["#0F3D1A", "#1E6B2C", "#2FA845", "#39FF14", "#B6FF9E"],
  chrome: ["#8E8EAF", "#B4B4D0", "#DADAF0", "#C7B8FF", "#FF7AD9"],
  iron: ["#DDDDDD", "#BBBBBB", "#999999", "#666666", "#FF3B4A"],
};

/**
 * Appendix B.1 (colours) and B.2 (type, shape, texture), one row per look.
 *
 * Note on fonts: §5.6's fifteen families arrive in Phase 2 step 5. Until they are bundled,
 * each look also carries `legacyFonts` — the closest of the six system stacks the app has
 * today — so a look renders sensibly now and upgrades when the real faces land.
 *
 * THREE DELIBERATE DEVIATIONS from Appendix B, all found by the §12.7 linter, which caught
 * the spec failing its own rule that `accent` must reach 3:1 against `bg`. All three are
 * light-background looks with a mid-tone accent:
 *
 *   Clinic     #2BD4BD on #FFFFFF = 1.87:1  ->  #21A392 = 3.12:1
 *   Retro '78  #D9822B on #F1DDB3 = 2.19:1  ->  #B46C24 = 3.08:1
 *   Studio     #7A9A7E on #EEE9DF = 2.57:1  ->  #6F8C73 = 3.05:1
 *
 * The rule is right and the palette was wrong: the accent colours chart bars, route lines
 * and rings, and a teal bar at 1.87:1 on white is genuinely hard to see. Each is the LEAST
 * darkening that clears the bar (77 %, 83 % and 91 % brightness respectively), applied as a
 * straight scale toward black so hue and saturation are untouched.
 */
const LOOKS = [
  // --- Quiet: the photo wins -------------------------------------------------
  {
    id: "clean",
    name: "Clean",
    family: "quiet",
    colors: {
      bg: "#111111",
      surface: "rgba(255,255,255,.10)",
      text: "#FFFFFF",
      textMuted: "rgba(255,255,255,.70)",
      accent: "#FFFFFF",
      accent2: "rgba(255,255,255,.50)",
    },
    zones: "default",
    legibility: "shadow",
    suits: ["any"],
    accentIsText: true,
    fonts: { display: "inter", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "sans", body: "sans" },
    type: { displayWeight: 800, uppercase: false, letterSpacing: -0.02 },
    shape: { radius: 16, glass: false },
    texture: { grain: 0, vignette: 0.25, pattern: null },
    motion: { ease: "outCubic", speed: 1, entrance: "slideUp", loop: null },
  },
  {
    id: "shade",
    name: "Shade",
    family: "quiet",
    colors: {
      bg: "#F2F2F2",
      surface: "rgba(0,0,0,.06)",
      text: "#0B0B0B",
      textMuted: "rgba(11,11,11,.60)",
      accent: "#0B0B0B",
      accent2: "#FFFFFF",
    },
    zones: "default",
    legibility: "scrim",
    suits: ["bright", "snow", "sky"],
    accentIsText: true,
    fonts: { display: "inter", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "sans", body: "sans" },
    type: { displayWeight: 800, uppercase: false, letterSpacing: -0.02 },
    shape: { radius: 16, glass: false },
    texture: { grain: 0, vignette: 0, pattern: null },
    motion: { ease: "outCubic", speed: 1, entrance: "slideUp", loop: null },
  },
  {
    id: "frost",
    name: "Frost",
    family: "quiet",
    colors: {
      bg: "#0B1220",
      surface: "rgba(255,255,255,.14)",
      text: "#FFFFFF",
      textMuted: "rgba(255,255,255,.72)",
      accent: "#5AC8FA",
      accent2: "#C7B8FF",
    },
    zones: "default",
    legibility: "pill",
    suits: ["any"],
    fonts: { display: "inter", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "sans", body: "sans" },
    type: { displayWeight: 700, uppercase: false, letterSpacing: -0.02 },
    shape: { radius: 24, glass: true },
    texture: { grain: 0, vignette: 0.3, pattern: null },
    motion: { ease: "outCubic", speed: 1, entrance: "scaleIn", loop: null },
  },
  {
    id: "film",
    name: "Film",
    family: "quiet",
    colors: {
      bg: "#1A1512",
      surface: "rgba(245,235,220,.10)",
      text: "#F3E9D8",
      textMuted: "rgba(243,233,216,.66)",
      accent: "#F3E9D8",
      accent2: "#C99A5B",
    },
    zones: "warm",
    legibility: "shadow",
    suits: ["golden hour", "forest"],
    accentIsText: true,
    fonts: { display: "fraunces", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "serif", body: "sans" },
    type: { displayWeight: 600, uppercase: false, letterSpacing: 0 },
    shape: { radius: 6, glass: false },
    texture: { grain: 0.14, vignette: 0.35, pattern: null },
    motion: { ease: "outCubic", speed: 0.9, entrance: "fadeIn", loop: null },
  },

  // --- Loud: night, track, speed --------------------------------------------
  {
    id: "volt",
    name: "Volt",
    family: "loud",
    colors: {
      bg: "#0E0E0E",
      surface: "rgba(255,255,255,.08)",
      text: "#F5F5F5",
      textMuted: "rgba(245,245,245,.66)",
      accent: "#D8FF3A",
      accent2: "#FFFFFF",
    },
    zones: "default",
    legibility: "shadow",
    suits: ["dark", "night"],
    fonts: { display: "bebas", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "cond", body: "sans" },
    type: { displayWeight: 400, uppercase: true, letterSpacing: 0.02 },
    shape: { radius: 8, glass: false },
    texture: { grain: 0.08, vignette: 0.35, pattern: null },
    motion: { ease: "spring", speed: 1.2, entrance: "slideUp", loop: "pulse" },
  },
  {
    id: "track",
    name: "Track",
    family: "loud",
    colors: {
      bg: "#141414",
      surface: "#1B1B1B",
      text: "#F2E8D5",
      textMuted: "rgba(242,232,213,.75)",
      accent: "#E8461E",
      accent2: "#FFD23F",
    },
    zones: "warm",
    legibility: "pill",
    suits: ["any"],
    fonts: { display: "anton", body: "grotesk", mono: "jetbrains" },
    legacyFonts: { display: "cond", body: "sans" },
    type: { displayWeight: 400, uppercase: true, letterSpacing: 0.04 },
    shape: { radius: 0, glass: false },
    texture: { grain: 0.15, vignette: 0.2, pattern: "stripes" },
    motion: { ease: "outExpo", speed: 1.15, entrance: "slideUp", loop: null },
  },
  {
    id: "flare",
    name: "Flare",
    family: "loud",
    colors: {
      bg: "#0D0B1A",
      surface: "rgba(255,255,255,.10)",
      text: "#FFFFFF",
      textMuted: "rgba(255,255,255,.70)",
      accent: "#FF2D95",
      accent2: "#2A5BFF",
    },
    zones: "neon",
    legibility: "shadow",
    suits: ["night", "city"],
    fonts: { display: "syne", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "sans", body: "sans" },
    type: { displayWeight: 800, uppercase: true, letterSpacing: 0.08 },
    shape: { radius: 28, glass: false },
    texture: { grain: 0.06, vignette: 0.35, pattern: null },
    motion: { ease: "spring", speed: 1.2, entrance: "scaleIn", loop: "pulse" },
  },
  {
    id: "ember",
    name: "Ember",
    family: "loud",
    colors: {
      bg: "#0F0A08",
      surface: "rgba(255,255,255,.08)",
      text: "#FFF4EC",
      textMuted: "rgba(255,244,236,.70)",
      accent: "#FF7A18",
      accent2: "#FFD166",
    },
    accentGradient: ["#FF7A18", "#FF2A2A"],
    zones: "warm",
    legibility: "scrim",
    suits: ["sunset", "dark"],
    fonts: { display: "archivo", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "cond", body: "sans" },
    type: { displayWeight: 400, uppercase: true, letterSpacing: 0.02 },
    shape: { radius: 12, glass: false },
    texture: { grain: 0.1, vignette: 0.4, pattern: null },
    motion: { ease: "outExpo", speed: 1.1, entrance: "slideUp", loop: null },
  },

  // --- Editorial: magazine, journal -----------------------------------------
  {
    id: "paper",
    name: "Paper",
    family: "editorial",
    colors: {
      bg: "#F4EFE6",
      surface: "rgba(0,0,0,.05)",
      text: "#1A1714",
      textMuted: "rgba(26,23,20,.62)",
      accent: "#1A1714",
      accent2: "#B8462E",
    },
    zones: "greys",
    legibility: "scrim",
    suits: ["soft light", "any"],
    accentIsText: true,
    fonts: { display: "fraunces", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "serif", body: "sans" },
    type: { displayWeight: 700, uppercase: false, letterSpacing: -0.01 },
    shape: { radius: 4, glass: false },
    texture: { grain: 0.12, vignette: 0.1, pattern: null },
    motion: { ease: "linear", speed: 0.8, entrance: "typewriter", loop: null },
  },
  {
    id: "broadsheet",
    name: "Broadsheet",
    family: "editorial",
    colors: {
      bg: "#FFFFFF",
      surface: "#F4F4F4",
      text: "#000000",
      textMuted: "#555555",
      accent: "#000000",
      accent2: "#C8102E",
    },
    zones: "greys",
    legibility: "pill",
    suits: ["any"],
    accentIsText: true,
    fonts: { display: "playfair", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "serif", body: "sans" },
    type: { displayWeight: 900, uppercase: false, letterSpacing: -0.01 },
    shape: { radius: 0, glass: false },
    texture: { grain: 0.05, vignette: 0, pattern: "rules" },
    motion: { ease: "linear", speed: 0.85, entrance: "fadeIn", loop: null },
  },
  {
    id: "journal",
    name: "Journal",
    family: "editorial",
    colors: {
      bg: "#FAF7F1",
      surface: "rgba(0,0,0,.04)",
      text: "#262220",
      textMuted: "rgba(38,34,32,.60)",
      accent: "#262220",
      accent2: "#8A6E4B",
    },
    zones: "sage",
    legibility: "scrim",
    suits: ["soft", "indoor"],
    accentIsText: true,
    fonts: { display: "instrument", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "serif", body: "sans" },
    type: { displayWeight: 400, uppercase: false, letterSpacing: 0.01 },
    shape: { radius: 2, glass: false },
    texture: { grain: 0.1, vignette: 0.05, pattern: null },
    motion: { ease: "linear", speed: 0.8, entrance: "fadeIn", loop: null },
  },
  {
    id: "zine",
    name: "Zine",
    family: "editorial",
    colors: {
      bg: "#EDE6D6",
      surface: "#111111",
      text: "#111111",
      textMuted: "rgba(17,17,17,.65)",
      accent: "#111111",
      accent2: "#FF3B30",
    },
    zones: "greys",
    legibility: "pill",
    suits: ["any"],
    accentIsText: true,
    fonts: { display: "archivo", body: "jetbrains", mono: "jetbrains" },
    legacyFonts: { display: "cond", body: "mono" },
    type: { displayWeight: 400, uppercase: true, letterSpacing: 0.02 },
    shape: { radius: 0, glass: false },
    texture: { grain: 0.2, vignette: 0.1, pattern: "halftone" },
    motion: { ease: "outCubic", speed: 1.1, entrance: "scaleIn", loop: null },
  },

  // --- Data: technical, nerdy -----------------------------------------------
  {
    id: "ledger",
    name: "Ledger",
    family: "data",
    colors: {
      bg: "#F7F3EA",
      surface: "#FFFFFF",
      text: "#111111",
      textMuted: "rgba(17,17,17,.60)",
      accent: "#111111",
      accent2: "#E8461E",
    },
    zones: "greys",
    legibility: "pill",
    suits: ["any"],
    accentIsText: true,
    fonts: { display: "jetbrains", body: "jetbrains", mono: "jetbrains" },
    legacyFonts: { display: "mono", body: "mono" },
    type: { displayWeight: 700, uppercase: true, letterSpacing: 0 },
    shape: { radius: 2, glass: false },
    texture: { grain: 0.06, vignette: 0, pattern: null },
    motion: { ease: "linear", speed: 1, entrance: "fadeIn", loop: null },
  },
  {
    id: "telemetry",
    name: "Telemetry",
    family: "data",
    colors: {
      bg: "#050806",
      surface: "rgba(57,255,20,.08)",
      text: "#39FF14",
      textMuted: "rgba(57,255,20,.60)",
      accent: "#39FF14",
      accent2: "#B6FF9E",
    },
    zones: "greens",
    legibility: "scrim",
    suits: ["dark", "night"],
    accentIsText: true,
    fonts: { display: "jetbrains", body: "jetbrains", mono: "jetbrains" },
    legacyFonts: { display: "mono", body: "mono" },
    type: { displayWeight: 700, uppercase: true, letterSpacing: 0.04 },
    shape: { radius: 2, glass: false },
    texture: { grain: 0.12, vignette: 0.5, pattern: "scanlines" },
    motion: { ease: "linear", speed: 1, entrance: "typewriter", loop: null },
  },
  {
    id: "blueprint",
    name: "Blueprint",
    family: "data",
    colors: {
      bg: "#0F3DA8",
      surface: "rgba(255,255,255,.10)",
      text: "#FFFFFF",
      textMuted: "rgba(255,255,255,.70)",
      accent: "#FFFFFF",
      accent2: "#9FC5FF",
    },
    zones: "blues",
    legibility: "scrim",
    suits: ["any"],
    accentIsText: true,
    fonts: { display: "grotesk", body: "jetbrains", mono: "jetbrains" },
    legacyFonts: { display: "sans", body: "mono" },
    type: { displayWeight: 700, uppercase: true, letterSpacing: 0.06 },
    shape: { radius: 0, glass: false },
    texture: { grain: 0.05, vignette: 0, pattern: "grid" },
    motion: { ease: "linear", speed: 1, entrance: "fadeIn", loop: null },
  },
  {
    id: "dashboard",
    name: "Dashboard",
    family: "data",
    colors: {
      bg: "#0F1720",
      surface: "rgba(255,255,255,.06)",
      text: "#E6EDF3",
      textMuted: "rgba(230,237,243,.60)",
      accent: "#3DDC97",
      accent2: "#FFB020",
    },
    zones: "default",
    legibility: "pill",
    suits: ["any"],
    fonts: { display: "inter", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "sans", body: "sans" },
    type: { displayWeight: 700, uppercase: false, letterSpacing: -0.01 },
    shape: { radius: 18, glass: false },
    texture: { grain: 0, vignette: 0.2, pattern: null },
    motion: { ease: "outCubic", speed: 1, entrance: "slideUp", loop: null },
  },

  // --- Health: effort, gym, wellness ----------------------------------------
  {
    id: "clinic",
    name: "Clinic",
    family: "health",
    colors: {
      bg: "#FFFFFF",
      surface: "#F3F5F7",
      text: "#0F172A",
      textMuted: "#64748B",
      accent: "#21A392",
      accent2: "#FF5A5F",
    },
    zones: "clinical",
    legibility: "pill",
    suits: ["bright", "indoor"],
    fonts: { display: "inter", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "sans", body: "sans" },
    type: { displayWeight: 700, uppercase: false, letterSpacing: -0.01 },
    shape: { radius: 20, glass: false },
    texture: { grain: 0, vignette: 0, pattern: null },
    motion: { ease: "outCubic", speed: 1, entrance: "slideUp", loop: "heartbeat" },
  },
  {
    id: "pulse",
    name: "Pulse",
    family: "health",
    colors: {
      bg: "#120608",
      surface: "rgba(255,90,95,.10)",
      text: "#FFFFFF",
      textMuted: "rgba(255,255,255,.70)",
      accent: "#FF3B4A",
      accent2: "#FF8A80",
    },
    zones: "hot",
    legibility: "shadow",
    suits: ["dark gym"],
    fonts: { display: "bebas", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "cond", body: "sans" },
    type: { displayWeight: 400, uppercase: true, letterSpacing: 0.04 },
    shape: { radius: 8, glass: false },
    texture: { grain: 0.06, vignette: 0.45, pattern: null },
    motion: { ease: "spring", speed: 1.2, entrance: "scaleIn", loop: "heartbeat" },
  },
  {
    id: "studio",
    name: "Studio",
    family: "health",
    colors: {
      bg: "#EEE9DF",
      surface: "rgba(0,0,0,.05)",
      text: "#2F3A34",
      textMuted: "rgba(47,58,52,.65)",
      accent: "#6F8C73",
      accent2: "#D8B08C",
    },
    zones: "sage",
    legibility: "scrim",
    suits: ["soft", "yoga", "indoor"],
    fonts: { display: "fraunces", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "serif", body: "sans" },
    type: { displayWeight: 500, uppercase: false, letterSpacing: 0.01 },
    shape: { radius: 24, glass: false },
    texture: { grain: 0.06, vignette: 0, pattern: null },
    motion: { ease: "outCubic", speed: 0.85, entrance: "fadeIn", loop: null },
  },
  {
    id: "iron",
    name: "Iron",
    family: "health",
    colors: {
      bg: "#0C0C0C",
      surface: "#1A1A1A",
      text: "#F5F5F5",
      textMuted: "rgba(245,245,245,.60)",
      accent: "#F5F5F5",
      accent2: "#9AA0A6",
    },
    zones: "iron",
    legibility: "shadow",
    suits: ["gym mirror", "dark"],
    accentIsText: true,
    fonts: { display: "shoulders", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "cond", body: "sans" },
    type: { displayWeight: 900, uppercase: true, letterSpacing: 0.05 },
    shape: { radius: 4, glass: false },
    texture: { grain: 0.18, vignette: 0.5, pattern: null },
    motion: { ease: "outExpo", speed: 1.1, entrance: "slideUp", loop: null },
  },

  // --- Fun: nostalgia, kit --------------------------------------------------
  {
    id: "neon",
    name: "Neon",
    family: "fun",
    colors: {
      bg: "#0A0614",
      surface: "rgba(255,45,149,.12)",
      text: "#FFFFFF",
      textMuted: "rgba(255,255,255,.70)",
      accent: "#FF2D95",
      accent2: "#5AC8FA",
    },
    zones: "neon",
    legibility: "shadow",
    suits: ["night"],
    fonts: { display: "monoton", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "cond", body: "sans" },
    type: { displayWeight: 400, uppercase: true, letterSpacing: 0.06 },
    shape: { radius: 12, glass: false },
    texture: { grain: 0.1, vignette: 0.45, pattern: null },
    motion: { ease: "spring", speed: 1.2, entrance: "scaleIn", loop: "flicker" },
  },
  {
    id: "retro78",
    name: "Retro '78",
    family: "fun",
    colors: {
      bg: "#F1DDB3",
      surface: "#2B1D14",
      text: "#2B1D14",
      textMuted: "rgba(43,29,20,.65)",
      accent: "#B46C24",
      accent2: "#8C2F1A",
    },
    zones: "warm",
    legibility: "pill",
    suits: ["any"],
    fonts: { display: "unbounded", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "cond", body: "sans" },
    type: { displayWeight: 900, uppercase: true, letterSpacing: 0.06 },
    shape: { radius: 0, glass: false },
    texture: { grain: 0.22, vignette: 0.15, pattern: "stripes" },
    motion: { ease: "outExpo", speed: 1.05, entrance: "slideUp", loop: null },
  },
  {
    id: "y2k",
    name: "Y2K",
    family: "fun",
    colors: {
      bg: "#1B1830",
      surface: "rgba(255,255,255,.12)",
      text: "#FFFFFF",
      textMuted: "rgba(255,255,255,.70)",
      accent: "#E4E4F5",
      accent2: "#C7B8FF",
    },
    accentGradient: ["#E4E4F5", "#8E8EAF"],
    zones: "chrome",
    legibility: "pill",
    suits: ["any"],
    accentIsText: true,
    fonts: { display: "syne", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "sans", body: "sans" },
    type: { displayWeight: 800, uppercase: false, letterSpacing: -0.01 },
    shape: { radius: 40, glass: true },
    texture: { grain: 0.02, vignette: 0.2, pattern: null },
    motion: { ease: "spring", speed: 1.15, entrance: "scaleIn", loop: null },
  },
  {
    id: "kit",
    name: "Kit",
    family: "fun",
    colors: {
      bg: "#1E1E1E",
      surface: "#F5F5F5",
      text: "#FFFFFF",
      textMuted: "rgba(255,255,255,.70)",
      accent: "#FFD23F",
      accent2: "#1F4FBF",
    },
    zones: "default",
    legibility: "pill",
    suits: ["any"],
    fonts: { display: "rubikmono", body: "inter", mono: "jetbrains" },
    legacyFonts: { display: "cond", body: "sans" },
    type: { displayWeight: 400, uppercase: true, letterSpacing: 0.02 },
    shape: { radius: 0, glass: false },
    texture: { grain: 0, vignette: 0.15, pattern: "stripes" },
    motion: { ease: "outExpo", speed: 1.1, entrance: "slideLeft", loop: null },
  },
];

mkdirSync(OUT, { recursive: true });

for (const look of LOOKS) {
  const json = {
    id: look.id,
    name: look.name,
    family: look.family,
    colors: look.colors,
    ...(look.accentGradient ? { accentGradient: look.accentGradient } : {}),
    fonts: look.fonts,
    legacyFonts: look.legacyFonts,
    shape: { radius: look.shape.radius, glass: look.shape.glass, stroke: 3, pad: 24 },
    type: {
      uppercase: look.type.uppercase,
      letterSpacing: look.type.letterSpacing,
      displayWeight: look.type.displayWeight,
      tabular: true,
    },
    texture: look.texture,
    legibility: look.legibility,
    chart: { zones: look.zones, zoneColors: ZONES[look.zones] },
    photo: { suits: look.suits },
    motion: look.motion,
    ...(look.accentIsText ? { accentIsText: true } : {}),
  };
  writeFileSync(resolve(OUT, `${look.id}.json`), `${JSON.stringify(json, null, 2)}\n`);
}

console.log(`wrote ${LOOKS.length} looks to src/looks/`);
